const Discord = require("discord.js");
module.exports.run = (bot, message, args) => {
	if (!args[0]) return message.reply("You must provide a timezone!");
	var search = args[0].toLowerCase();
	var offSet;
	if (search === ("aksd")) offSet = -9;
	if (search === ("a")) offSet = 1;
	if (search === ("akdt")) offSet = -8;
	if (search === ("ast")) offSet = -4;
	if (search === ("adt")) offSet = -3;
	if (search === ("act")) offSet = -5;
	if (search === ("aedt")) offSet = 11;
	if (search === ("aest")) offSet = 10;
	if (search === ("aet")) offSet = 1;
	if (search === ("almt")) offSet = 6;
	if (search === ("anast")) offSet = 12;
	if (search === ("anat")) offSet = 12;
	if (search === ("aqtt")) offSet = 5;
	if (search === ("art")) offSet = -3;
	if (search === ("awdt")) offSet = 9;
	if (search === ("awst")) offSet = 8;
	if (search === ("azost")) offSet = 0;
	if (search === ("azot")) offSet = -1;
	if (search === ("azst")) offSet = 5;
	if (search === ("azt")) offSet = 4;
	if (search === ("aoe")) offSet = -12;
	if (search === ("b")) offSet = 2;
	if (search === ("bnt")) offSet = 8;
	if (search === ("bot")) offSet = -4;
	if (search === ("brst")) offSet = -2;
	if (search === ("brt")) offSet = -3;
	if (search === ("btt")) offSet = 6;
	if (search === ("c")) offSet = 3;
	if (search === ("cast")) offSet = 8;
	if (search === ("cat")) offSet = 2;
	if (search === ("cest")) offSet = 2;
	if (search === ("cet")) offSet = 1;
	if (search === ("chost")) offSet = 9;
	if (search === ("chot")) offSet = 8;
	if (search === ("chut")) offSet = 10;
	if (search === ("cidst")) offSet = -4;
	if (search === ("cist")) offSet = -5;
	if (search === ("ckt")) offSet = -10;
	if (search === ("clst")) offSet = -3;
	if (search === ("clt")) offSet = -4;
	if (search === ("cot")) offSet = -5;
	if (search === ("cst")) offSet = -6;
	if (search === ("cdt")) offSet = -5;
	if (search === ("cvt")) offSet = -1;
	if (search === ("cxt")) offSet = 7;
	if (search === ("chst")) offSet = 10;
	if (search === ("d")) offSet = 4;
	if (search === ("davt")) offSet = 7;
	if (search === ("ddut")) offSet = 10;
	if (search === ("e")) offSet = 5;
	if (search === ("easst")) offSet = -5;
	if (search === ("east")) offSet = -6;
	if (search === ("eat")) offSet = 3;
	if (search === ("ect")) offSet = -5;
	if (search === ("est")) offSet = -5;
	if (search === ("edt")) offSet = -4;
	if (search === ("eest")) offSet = 3;
	if (search === ("eet")) offSet = 2;
	if (search === ("egst")) offSet = 0;
	if (search === ("egt")) offSet = -1;
	if (search === ("f")) offSet = 6;
	if (search === ("fet")) offSet = 3;
	if (search === ("fjst")) offSet = 13;
	if (search === ("fjt")) offSet = 12;
	if (search === ("fkst")) offSet = -3;
	if (search === ("fkt")) offSet = -4;
	if (search === ("fnt")) offSet = -2;
	if (search === ("g")) offSet = 7;
	if (search === ("galt")) offSet = -6;
	if (search === ("gamt")) offSet = -9;
	if (search === ("get")) offSet = 4;
	if (search === ("gft")) offSet = -3;
	if (search === ("gilt")) offSet = 12;
	if (search === ("gmt")) offSet = 0;
	if (search === ("gyt")) offSet = -4;
	if (search === ("h")) offSet = 8;
	if (search === ("hdt")) offSet = -9;
	if (search === ("hkt")) offSet = 8;
	if (search === ("hovst")) offSet = 8;
	if (search === ("hovt")) offSet = 7;
	if (search === ("hst")) offSet = -10;
	if (search === ("hast")) offSet = -10;
	if (search === ("hadt")) offSet = -9;
	if (search === ("i")) offSet = 9;
	if (search === ("ict")) offSet = 7;
	if (search === ("idt")) offSet = 3;
	if (search === ("iot")) offSet = 6;
	if (search === ("irkst")) offSet = 9;
	if (search === ("irkt")) offSet = 8;
	if (search === ("jst")) offSet = 9;
	if (search === ("k")) offSet = 10;
	if (search === ("kgt")) offSet = 6;
	if (search === ("kost")) offSet = 11;
	if (search === ("krast")) offSet = 8;
	if (search === ("krat")) offSet = 7;
	if (search === ("kst")) offSet = 9;
	if (search === ("kuyt")) offSet = 4;
	if (search === ("l")) offSet = 11;
	if (search === ("lhdt")) offSet = 11;
	if (search === ("lint")) offSet = 14;
	if (search === ("m")) offSet = 12;
	if (search === ("magst")) offSet = 12;
	if (search === ("magt")) offSet = 11;
	if (search === ("mawt")) offSet = 5;
	if (search === ("mst")) offSet = -7;
	if (search === ("mdt")) offSet = -6;
	if (search === ("mht")) offSet = 12;
	if (search === ("msd")) offSet = 4;
	if (search === ("msk")) offSet = 3;
	if (search === ("mut")) offSet = 4;
	if (search === ("mvt")) offSet = 5;
	if (search === ("myt")) offSet = 8;
	if (search === ("n")) offSet = -1;
	if (search === ("nct")) offSet = 11;
	if (search === ("nft")) offSet = 11;
	if (search === ("novst")) offSet = 7;
	if (search === ("novt")) offSet = 6;
	if (search === ("nrt")) offSet = 12;
	if (search === ("nut")) offSet = -11;
	if (search === ("nzdt")) offSet = 13;
	if (search === ("nzst")) offSet = 12;
	if (search === ("o")) offSet = -2;
	if (search === ("omsst")) offSet = 7;
	if (search === ("omst")) offSet = 6;
	if (search === ("orat")) offSet = 5;
	if (search === ("p")) offSet = -3;
	if (search === ("pst")) offSet = -8;
	if (search === ("pdt")) offSet = -7;
	if (search === ("pet")) offSet = -5;
	if (search === ("petst")) offSet = 12;
	if (search === ("pett")) offSet = 12;
	if (search === ("pgt")) offSet = 10;
	if (search === ("phot")) offSet = 13;
	if (search === ("pht")) offSet = 8;
	if (search === ("pkt")) offSet = 5;
	if (search === ("pmdt")) offSet = -2;
	if (search === ("pmst")) offSet = -3;
	if (search === ("pont")) offSet = 11;
	if (search === ("pwt")) offSet = 9;
	if (search === ("pyst")) offSet = -3;
	if (search === ("q")) offSet = -4;
	if (search === ("qyzt")) offSet = 6;
	if (search === ("r")) offSet = -5;
	if (search === ("ret")) offSet = 4;
	if (search === ("rott")) offSet = -3;
	if (search === ("s")) offSet = -6;
	if (search === ("sakt")) offSet = 11;
	if (search === ("samt")) offSet = 4;
	if (search === ("sast")) offSet = 2;
	if (search === ("sbt")) offSet = 11;
	if (search === ("sct")) offSet = 4;
	if (search === ("sgt")) offSet = 8;
	if (search === ("sret")) offSet = 11;
	if (search === ("srt")) offSet = -3;
	if (search === ("sst")) offSet = -11;
	if (search === ("syot")) offSet = 3;
	if (search === ("t")) offSet = -7;
	if (search === ("taht")) offSet = -10;
	if (search === ("tft")) offSet = 5;
	if (search === ("tjt")) offSet = 5;
	if (search === ("tkt")) offSet = 13;
	if (search === ("tlt")) offSet = 9;
	if (search === ("tmt")) offSet = 5;
	if (search === ("tost")) offSet = 14;
	if (search === ("tot")) offSet = 13;
	if (search === ("trt")) offSet = 3;
	if (search === ("tvt")) offSet = 12;
	if (search === ("u")) offSet = -8;
	if (search === ("ulast")) offSet = 9;
	if (search === ("ulat")) offSet = 8;
	if (search === ("uyst")) offSet = -2;
	if (search === ("uyt")) offSet = -3;
	if (search === ("uzt")) offSet = 5;
	if (search === ("utc")) offSet = 0;
	if (search === ("v")) offSet = -9;
	if (search === ("vet")) offSet = -4;
	if (search === ("vlast")) offSet = 11;
	if (search === ("vlat")) offSet = 10;
	if (search === ("vost")) offSet = 6;
	if (search === ("vut")) offSet = 11;
	if (search === ("w")) offSet = -10;
	if (search === ("wakt")) offSet = 12;
	if (search === ("warst")) offSet = -3;
	if (search === ("wast")) offSet = 2;
	if (search === ("wat")) offSet = 1;
	if (search === ("west")) offSet = 1;
	if (search === ("wet")) offSet = 0;
	if (search === ("wft")) offSet = 12;
	if (search === ("wgst")) offSet = -2;
	if (search === ("wgt")) offSet = -3;
	if (search === ("wib")) offSet = 7;
	if (search === ("wit")) offSet = 9;
	if (search === ("wita")) offSet = 8;
	if (search === ("wt")) offSet = 0;
	if (search === ("x")) offSet = -11;
	if (search === ("y")) offSet = -12;
	if (search === ("yakst")) offSet = 10;
	if (search === ("yakt")) offSet = 9;
	if (search === ("yapt")) offSet = 10;
	if (search === ("yekst")) offSet = 6;
	if (search === ("yekt")) offSet = 5;
	if (search === ("z")) offSet = 0;
	if (!offSet) return message.reply("Time-zone not found or not supported at this time!");
	offSet *= 3600000;
	var date = new Date(Date.now() + offSet);
	var hours;
	var timeOfDay;
	if (date.getHours() > 12) {
		hours = date.getHours() - 12;
		timeOfDay = "PM";
	} else {
		hours = date.getHours();
		timeOfDay = "AM";
	}
	console.log(date.toString());
	var timeEmbed = new Discord.RichEmbed()
		.setTitle(`Date/Time In ${search.toUpperCase()}`)
		.setColor("ORANGE")
		.addField("Time", `${hours}:${date.getMinutes()} ${timeOfDay}`)
		.addField("Date", `${date.getMonth()}/${date.getDate()}/${date.getFullYear()}`)
		.setFooter(`Ran by ${message.author.tag}`);
	message.channel.send(timeEmbed);
};
module.exports.help = {
	name: "time",
	description: "Shows the time in a different timezone",
	type: "Information"
};
